edition = "2024"

# General formatting
max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Imports
imports_granularity="Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Code structure
match_block_trailing_comma = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true

# Control flow and blocks
control_brace_style = "AlwaysSameLine"
fn_single_line = false
where_single_line = false
force_multiline_blocks = false

# Comments and documentation
wrap_comments = true
comment_width = 80
normalize_comments = true
format_code_in_doc_comments = true

# Miscellaneous
condense_wildcard_suffixes = true
format_strings = true
hex_literal_case = "Upper"