[package]
name = "heroku-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
heroku-api = { path = "../api" }
heroku-registry = { path = "../registry" }
heroku-engine = { path = "../engine" }
heroku-tui = { path = "../tui" }
heroku-util = {path = "../util" }
reqwest = { workspace = true }