[package]
name = "heroku-util"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = { workspace = true }
once_cell = { workspace = true }
chrono = "0.4"

[build-dependencies]
serde_json = { workspace = true }
