[package]
name = "heroku-registry"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
heroku-registry-gen = { path = "../registry-gen" }
