[package]
name = "heroku-api"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
dirs-next = { workspace = true }
