[package]
name = "heroku-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
