[package]
name = "heroku-tui"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
heroku-registry = { path = "../registry" }
heroku-util = { path = "../util" }
arboard = "3"
