[package]
name = "heroku-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
heroku-registry = { path = "../registry" }
heroku-util = { path = "../util" }
heroku-types = { path = "../types" }
arboard = "3"
heroku-api = { path = "../api" }
tokio = { workspace = true }
futures-util = "0.3"
heck = { workspace = true }
chrono = "0.4"
regex = { workspace = true }
once_cell = { workspace = true }

[lib]
doctest = false

[build-dependencies]
serde_json = { workspace = true }
