[package]
name = "heroku-registry-gen"
version = "0.1.0"
edition = "2018"
readme = "README.md"

[lib]
path = "src/lib.rs"

[[bin]]
name = "schema-to-manifest"
path = "src/bin/schema_to_manifest.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
percent-encoding = { workspace = true }
heck = { workspace = true }
heroku-registry-types = { path = "../registry-types" }
